name: JobParallelRun
on: 
  workflow_dispatch:
jobs:
  job1_BuildVM:
    runs-on: ubuntu-latest
    steps:
      - name: my-step1 on Build VM job
        run: echo "First Step Build the VM!"
  job2_PublishVM:
    runs-on: ubuntu-latest
    steps:
      - name: my-step1 on Publish VM job
        run: echo "First Step of Publish the VM!"      
