name: SimpleManualWF_3Env
on: push
jobs:
  Dev:
    runs-on: ubuntu-latest
    environment: Dev
    steps:
      -uses: actions/checkout@v2
      
      -name: Run a script
        run:|
          echo "I'm running on Dev Environment!"
  QA:
    runs-on: ubuntu-latest
    environment: QA
    needs: Dev
    steps:
      -uses: actions/checkout@v2
      
      -name: Run a script
        run:|
          echo "I'm running on QA Environment!"
  Prod:
    runs-on: ubuntu-latest
    environment: QA
    needs: QA
    steps:
      -uses: actions/checkout@v2
      
      -name: Run a script
        run:|
          echo "I'm running on Prod Environment!"
